import { Product, Feedback, DEFAULT_CATEGORIES, DEFAULT_AI_PROMPTS } from '@/types';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'TechFlow Pro',
    description: 'Enterprise project management and collaboration platform',
    industry: 'tech',
    config: {
      categories: DEFAULT_CATEGORIES.tech,
      aiPrompt: DEFAULT_AI_PROMPTS.tech,
      focusAreas: ['Performance optimization', 'User experience', 'Security vulnerabilities'],
    },
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'prod-2',
    name: 'HealthFirst Clinic',
    description: 'Multi-specialty healthcare facility serving the community',
    industry: 'healthcare',
    config: {
      categories: DEFAULT_CATEGORIES.healthcare,
      aiPrompt: DEFAULT_AI_PROMPTS.healthcare,
      focusAreas: ['Patient safety', 'Wait time reduction', 'Staff training'],
    },
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'prod-3',
    name: 'MetroBuild Infrastructure',
    description: 'Urban development and construction projects',
    industry: 'infrastructure',
    config: {
      categories: DEFAULT_CATEGORIES.infrastructure,
      aiPrompt: DEFAULT_AI_PROMPTS.infrastructure,
      focusAreas: ['Safety compliance', 'Timeline adherence', 'Quality standards'],
    },
    createdAt: new Date('2024-03-10'),
  },
];

export const mockFeedback: Feedback[] = [
  // TechFlow Pro feedback
  {
    id: 'fb-1',
    productId: 'prod-1',
    text: 'The dashboard takes forever to load when we have more than 100 projects. Really frustrating for our team.',
    rating: 2,
    email: 'john@company.com',
    createdAt: new Date('2024-12-01'),
    analysis: {
      sentiment: 'negative',
      category: 'Performance',
      priority: 'high',
      summary: 'Dashboard performance degrades significantly with large project counts, causing productivity loss.',
    },
  },
  {
    id: 'fb-2',
    productId: 'prod-1',
    text: 'Love the new dark mode feature! Makes working late much easier on the eyes.',
    rating: 5,
    createdAt: new Date('2024-12-05'),
    analysis: {
      sentiment: 'positive',
      category: 'UI/UX',
      priority: 'low',
      summary: 'User appreciates the dark mode feature for improved comfort during extended use.',
    },
  },
  {
    id: 'fb-3',
    productId: 'prod-1',
    text: 'Would be great to have Slack integration for notifications. Currently have to check both apps constantly.',
    rating: 3,
    email: 'sarah@startup.io',
    createdAt: new Date('2024-12-08'),
    analysis: {
      sentiment: 'neutral',
      category: 'Feature Request',
      priority: 'medium',
      summary: 'Request for Slack integration to streamline notification workflow.',
    },
  },
  {
    id: 'fb-4',
    productId: 'prod-1',
    text: 'Found a bug where file uploads fail silently. No error message, just nothing happens.',
    rating: 1,
    createdAt: new Date('2024-12-10'),
    analysis: {
      sentiment: 'negative',
      category: 'Bug Report',
      priority: 'high',
      summary: 'Critical UX issue with silent file upload failures requiring immediate attention.',
    },
  },
  {
    id: 'fb-5',
    productId: 'prod-1',
    text: 'The API documentation is excellent. Made integration a breeze!',
    rating: 5,
    email: 'dev@techcorp.com',
    createdAt: new Date('2024-12-12'),
    analysis: {
      sentiment: 'positive',
      category: 'Documentation',
      priority: 'low',
      summary: 'Positive feedback on API documentation quality facilitating easy integration.',
    },
  },
  {
    id: 'fb-6',
    productId: 'prod-1',
    text: 'Mobile app keeps crashing when switching between projects. Using iPhone 14.',
    rating: 2,
    createdAt: new Date('2024-12-14'),
    analysis: {
      sentiment: 'negative',
      category: 'Bug Report',
      priority: 'high',
      summary: 'Mobile app stability issue on iOS causing crashes during project navigation.',
    },
  },
  {
    id: 'fb-7',
    productId: 'prod-1',
    text: 'Overall solid product. A few rough edges but getting the job done.',
    rating: 4,
    createdAt: new Date('2024-12-15'),
    analysis: {
      sentiment: 'positive',
      category: 'UI/UX',
      priority: 'low',
      summary: 'Generally positive review acknowledging product utility despite minor issues.',
    },
  },
  {
    id: 'fb-8',
    productId: 'prod-1',
    text: 'Security concern: session doesn\'t expire even after 24 hours of inactivity.',
    rating: 2,
    email: 'security@enterprise.com',
    createdAt: new Date('2024-12-16'),
    analysis: {
      sentiment: 'negative',
      category: 'Security',
      priority: 'high',
      summary: 'Security vulnerability identified with session management requiring urgent review.',
    },
  },

  // HealthFirst Clinic feedback
  {
    id: 'fb-9',
    productId: 'prod-2',
    text: 'Dr. Smith was incredibly attentive and explained everything clearly. Best experience I\'ve had.',
    rating: 5,
    createdAt: new Date('2024-12-02'),
    analysis: {
      sentiment: 'positive',
      category: 'Staff Behavior',
      priority: 'low',
      summary: 'Excellent patient experience with clear communication from Dr. Smith.',
    },
  },
  {
    id: 'fb-10',
    productId: 'prod-2',
    text: 'Waited 2 hours past my appointment time. No one informed me about the delay.',
    rating: 1,
    email: 'frustrated@email.com',
    createdAt: new Date('2024-12-05'),
    analysis: {
      sentiment: 'negative',
      category: 'Wait Time',
      priority: 'high',
      summary: 'Significant wait time issue compounded by lack of communication to patient.',
    },
  },
  {
    id: 'fb-11',
    productId: 'prod-2',
    text: 'The new online booking system is convenient. Easy to reschedule appointments.',
    rating: 4,
    createdAt: new Date('2024-12-08'),
    analysis: {
      sentiment: 'positive',
      category: 'Facilities',
      priority: 'low',
      summary: 'Positive reception of digital booking system improving patient convenience.',
    },
  },
  {
    id: 'fb-12',
    productId: 'prod-2',
    text: 'Restrooms need better maintenance. Found them unclean during my visit.',
    rating: 2,
    createdAt: new Date('2024-12-10'),
    analysis: {
      sentiment: 'negative',
      category: 'Hygiene',
      priority: 'medium',
      summary: 'Facility hygiene concerns regarding restroom maintenance standards.',
    },
  },
  {
    id: 'fb-13',
    productId: 'prod-2',
    text: 'Billing department resolved my insurance issue quickly. Very professional.',
    rating: 4,
    email: 'patient123@mail.com',
    createdAt: new Date('2024-12-12'),
    analysis: {
      sentiment: 'positive',
      category: 'Billing',
      priority: 'low',
      summary: 'Efficient billing department handling insurance-related queries professionally.',
    },
  },
  {
    id: 'fb-14',
    productId: 'prod-2',
    text: 'Treatment was effective but felt rushed. Would appreciate more time with the doctor.',
    rating: 3,
    createdAt: new Date('2024-12-14'),
    analysis: {
      sentiment: 'neutral',
      category: 'Treatment Quality',
      priority: 'medium',
      summary: 'Effective treatment but concerns about consultation time allocation.',
    },
  },

  // MetroBuild Infrastructure feedback
  {
    id: 'fb-15',
    productId: 'prod-3',
    text: 'Workers not wearing safety helmets at the downtown site. This is dangerous!',
    rating: 1,
    email: 'concerned.citizen@email.com',
    createdAt: new Date('2024-12-03'),
    analysis: {
      sentiment: 'negative',
      category: 'Safety Concerns',
      priority: 'high',
      summary: 'Critical safety violation observed with workers lacking proper protective equipment.',
    },
  },
  {
    id: 'fb-16',
    productId: 'prod-3',
    text: 'The highway expansion is 3 months behind schedule. When will it be completed?',
    rating: 2,
    createdAt: new Date('2024-12-06'),
    analysis: {
      sentiment: 'negative',
      category: 'Project Delays',
      priority: 'medium',
      summary: 'Significant project timeline deviation causing public concern about completion.',
    },
  },
  {
    id: 'fb-17',
    productId: 'prod-3',
    text: 'The new bridge looks fantastic and the construction team kept the area clean.',
    rating: 5,
    createdAt: new Date('2024-12-09'),
    analysis: {
      sentiment: 'positive',
      category: 'Quality Issues',
      priority: 'low',
      summary: 'Positive feedback on project quality and site maintenance during construction.',
    },
  },
  {
    id: 'fb-18',
    productId: 'prod-3',
    text: 'Noise levels during night work are unbearable. Affecting the whole neighborhood.',
    rating: 1,
    email: 'resident@neighborhood.com',
    createdAt: new Date('2024-12-11'),
    analysis: {
      sentiment: 'negative',
      category: 'Environmental',
      priority: 'high',
      summary: 'Community disturbance from night construction work requiring noise mitigation.',
    },
  },
  {
    id: 'fb-19',
    productId: 'prod-3',
    text: 'Project updates on the website are helpful. Keep the community informed!',
    rating: 4,
    createdAt: new Date('2024-12-13'),
    analysis: {
      sentiment: 'positive',
      category: 'Communication',
      priority: 'low',
      summary: 'Appreciation for transparent project communication through digital channels.',
    },
  },
];
