/**
 * Static industry → category catalog.
 * Mirrors backend/input_data/Industry_Master_Labels.json so create/settings
 * UIs do not need a network round-trip for this reference data.
 */
export const INDUSTRY_CATEGORY_CATALOG: Record<string, string[]> = {
  Technology: [
    "Bug Report",
    "Performance Issue",
    "Feature Request",
    "User Experience",
    "Documentation Request",
    "Security Concern",
    "Integration Issue",
    "API Issue",
    "Login Issue",
    "Data Loss",
    "Crash",
    "Scalability",
    "Compatibility",
    "Deployment",
    "Configuration",
    "Accessibility",
    "Payment",
    "Notification",
    "Search",
  ],
  Healthcare: [
    "Staff Behavior",
    "Doctor Communication",
    "Nursing Care",
    "Wait Time",
    "Appointment Scheduling",
    "Facilities",
    "Cleanliness",
    "Treatment Quality",
    "Diagnosis Accuracy",
    "Medication Issue",
    "Billing",
    "Insurance Issue",
    "Emergency Care",
    "Patient Safety",
    "Medical Records",
    "Discharge Process",
    "Accessibility",
    "Equipment Quality",
    "Hygiene",
  ],
  Infrastructure: [
    "Safety Concern",
    "Project Delay",
    "Construction Quality",
    "Material Quality",
    "Communication Issue",
    "Cost Overrun",
    "Environmental Impact",
    "Permit Issue",
    "Design Flaw",
    "Inspection Issue",
    "Labor Issue",
    "Equipment Failure",
    "Road Quality",
    "Structural Integrity",
    "Maintenance Issue",
    "Vendor Issue",
    "Timeline Planning",
    "Weather Impact",
    "Site Management",
  ],
  Education: [
    "Teaching Quality",
    "Curriculum Content",
    "Exam Evaluation",
    "Faculty Behavior",
    "Class Scheduling",
    "Facilities",
    "Laboratory Equipment",
    "Library Resources",
    "Fees",
    "Administration",
    "Student Support",
    "Placement Support",
    "Internship Opportunities",
    "Online Learning",
    "Attendance Policy",
    "Assessment Methods",
    "Counseling Services",
    "Accessibility",
    "Hostel Facilities",
  ],
  Retail: [
    "Product Quality",
    "Damaged Product",
    "Wrong Item Delivered",
    "Delivery Delay",
    "Customer Service",
    "Pricing Issue",
    "Discount Issue",
    "Payment Issue",
    "Refund Delay",
    "Return Process",
    "Packaging Issue",
    "Inventory Availability",
    "Store Experience",
    "Website/App Issue",
    "Loyalty Program",
    "Warranty Issue",
    "Fraud Concern",
    "Order Tracking",
    "Exchange Issue",
  ],
  Hospitality: [
    "Staff Behavior",
    "Cleanliness",
    "Room Quality",
    "Bathroom Cleanliness",
    "Food Quality",
    "Food Service",
    "Check-in Experience",
    "Check-out Experience",
    "Billing Issue",
    "Pricing Concern",
    "Noise Issue",
    "Amenities",
    "WiFi Issue",
    "Maintenance Issue",
    "Housekeeping",
    "Safety Concern",
    "Accessibility",
    "Parking Issue",
    "Location Convenience",
  ],
};

export const INDUSTRY_OPTIONS = Object.keys(INDUSTRY_CATEGORY_CATALOG);

export function getCategoriesForIndustry(industry: string): string[] {
  return INDUSTRY_CATEGORY_CATALOG[industry] ?? [];
}
